// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PriceType_Name int32

const (
	PriceType_UNKNOWN PriceType_Name = 0
	PriceType_OPEN    PriceType_Name = 1
	PriceType_CLOSE   PriceType_Name = 2
)

var PriceType_Name_name = map[int32]string{
	0: "UNKNOWN",
	1: "OPEN",
	2: "CLOSE",
}

var PriceType_Name_value = map[string]int32{
	"UNKNOWN": 0,
	"OPEN":    1,
	"CLOSE":   2,
}

func (x PriceType_Name) String() string {
	return proto.EnumName(PriceType_Name_name, int32(x))
}

func (PriceType_Name) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{1, 0}
}

type OpenType_Name int32

const (
	OpenType_UNKNOWN OpenType_Name = 0
	OpenType_NORMAL  OpenType_Name = 1
	OpenType_REVERSE OpenType_Name = 2
)

var OpenType_Name_name = map[int32]string{
	0: "UNKNOWN",
	1: "NORMAL",
	2: "REVERSE",
}

var OpenType_Name_value = map[string]int32{
	"UNKNOWN": 0,
	"NORMAL":  1,
	"REVERSE": 2,
}

func (x OpenType_Name) String() string {
	return proto.EnumName(OpenType_Name_name, int32(x))
}

func (OpenType_Name) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{2, 0}
}

type Rule_Indicator_SimpleMovingAverage_Condition int32

const (
	Rule_Indicator_SimpleMovingAverage_UNKNOWN           Rule_Indicator_SimpleMovingAverage_Condition = 0
	Rule_Indicator_SimpleMovingAverage_ABOVE_SIGNAL_LINE Rule_Indicator_SimpleMovingAverage_Condition = 1
	Rule_Indicator_SimpleMovingAverage_BELOW_SIGNAL_LINE Rule_Indicator_SimpleMovingAverage_Condition = 2
)

var Rule_Indicator_SimpleMovingAverage_Condition_name = map[int32]string{
	0: "UNKNOWN",
	1: "ABOVE_SIGNAL_LINE",
	2: "BELOW_SIGNAL_LINE",
}

var Rule_Indicator_SimpleMovingAverage_Condition_value = map[string]int32{
	"UNKNOWN":           0,
	"ABOVE_SIGNAL_LINE": 1,
	"BELOW_SIGNAL_LINE": 2,
}

func (x Rule_Indicator_SimpleMovingAverage_Condition) String() string {
	return proto.EnumName(Rule_Indicator_SimpleMovingAverage_Condition_name, int32(x))
}

func (Rule_Indicator_SimpleMovingAverage_Condition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3, 0, 0, 0}
}

type Rule_Indicator_RelativeStrengthIndex_Condition int32

const (
	Rule_Indicator_RelativeStrengthIndex_UNKNOWN                Rule_Indicator_RelativeStrengthIndex_Condition = 0
	Rule_Indicator_RelativeStrengthIndex_ABOVE_OVER_BOUGHT_LINE Rule_Indicator_RelativeStrengthIndex_Condition = 1
	Rule_Indicator_RelativeStrengthIndex_BELOW_OVER_BOUGHT_LINE Rule_Indicator_RelativeStrengthIndex_Condition = 2
	Rule_Indicator_RelativeStrengthIndex_ABOVE_UNDER_SOLD_LINE  Rule_Indicator_RelativeStrengthIndex_Condition = 3
	Rule_Indicator_RelativeStrengthIndex_BELOW_UNDER_SOLD_LINE  Rule_Indicator_RelativeStrengthIndex_Condition = 4
)

var Rule_Indicator_RelativeStrengthIndex_Condition_name = map[int32]string{
	0: "UNKNOWN",
	1: "ABOVE_OVER_BOUGHT_LINE",
	2: "BELOW_OVER_BOUGHT_LINE",
	3: "ABOVE_UNDER_SOLD_LINE",
	4: "BELOW_UNDER_SOLD_LINE",
}

var Rule_Indicator_RelativeStrengthIndex_Condition_value = map[string]int32{
	"UNKNOWN":                0,
	"ABOVE_OVER_BOUGHT_LINE": 1,
	"BELOW_OVER_BOUGHT_LINE": 2,
	"ABOVE_UNDER_SOLD_LINE":  3,
	"BELOW_UNDER_SOLD_LINE":  4,
}

func (x Rule_Indicator_RelativeStrengthIndex_Condition) String() string {
	return proto.EnumName(Rule_Indicator_RelativeStrengthIndex_Condition_name, int32(x))
}

func (Rule_Indicator_RelativeStrengthIndex_Condition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3, 0, 1, 0}
}

type Status_Name int32

const (
	Status_UNKNOWN Status_Name = 0
	Status_ENABLED Status_Name = 1
	Status_PAUSED  Status_Name = 2
)

var Status_Name_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENABLED",
	2: "PAUSED",
}

var Status_Name_value = map[string]int32{
	"UNKNOWN": 0,
	"ENABLED": 1,
	"PAUSED":  2,
}

func (x Status_Name) String() string {
	return proto.EnumName(Status_Name_name, int32(x))
}

func (Status_Name) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{4, 0}
}

type Direction_Name int32

const (
	Direction_UNKNOWN Direction_Name = 0
	Direction_BUY     Direction_Name = 1
	Direction_SELL    Direction_Name = 2
)

var Direction_Name_name = map[int32]string{
	0: "UNKNOWN",
	1: "BUY",
	2: "SELL",
}

var Direction_Name_value = map[string]int32{
	"UNKNOWN": 0,
	"BUY":     1,
	"SELL":    2,
}

func (x Direction_Name) String() string {
	return proto.EnumName(Direction_Name_name, int32(x))
}

func (Direction_Name) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{5, 0}
}

type Symbol_Name int32

const (
	Symbol_UNKNOWN Symbol_Name = 0
	Symbol_EUR_USD Symbol_Name = 1
	Symbol_USD_GBP Symbol_Name = 2
)

var Symbol_Name_name = map[int32]string{
	0: "UNKNOWN",
	1: "EUR_USD",
	2: "USD_GBP",
}

var Symbol_Name_value = map[string]int32{
	"UNKNOWN": 0,
	"EUR_USD": 1,
	"USD_GBP": 2,
}

func (x Symbol_Name) String() string {
	return proto.EnumName(Symbol_Name_name, int32(x))
}

func (Symbol_Name) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{7, 0}
}

type Candlestick struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Current              int64                `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Low                  int64                `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	High                 int64                `protobuf:"varint,4,opt,name=high,proto3" json:"high,omitempty"`
	Open                 int64                `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	Close                int64                `protobuf:"varint,6,opt,name=close,proto3" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Candlestick) Reset()         { *m = Candlestick{} }
func (m *Candlestick) String() string { return proto.CompactTextString(m) }
func (*Candlestick) ProtoMessage()    {}
func (*Candlestick) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{0}
}

func (m *Candlestick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candlestick.Unmarshal(m, b)
}
func (m *Candlestick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candlestick.Marshal(b, m, deterministic)
}
func (m *Candlestick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candlestick.Merge(m, src)
}
func (m *Candlestick) XXX_Size() int {
	return xxx_messageInfo_Candlestick.Size(m)
}
func (m *Candlestick) XXX_DiscardUnknown() {
	xxx_messageInfo_Candlestick.DiscardUnknown(m)
}

var xxx_messageInfo_Candlestick proto.InternalMessageInfo

func (m *Candlestick) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Candlestick) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *Candlestick) GetLow() int64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Candlestick) GetHigh() int64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Candlestick) GetOpen() int64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Candlestick) GetClose() int64 {
	if m != nil {
		return m.Close
	}
	return 0
}

type PriceType struct {
	Name                 PriceType_Name `protobuf:"varint,1,opt,name=name,proto3,enum=protos.PriceType_Name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PriceType) Reset()         { *m = PriceType{} }
func (m *PriceType) String() string { return proto.CompactTextString(m) }
func (*PriceType) ProtoMessage()    {}
func (*PriceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{1}
}

func (m *PriceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceType.Unmarshal(m, b)
}
func (m *PriceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceType.Marshal(b, m, deterministic)
}
func (m *PriceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceType.Merge(m, src)
}
func (m *PriceType) XXX_Size() int {
	return xxx_messageInfo_PriceType.Size(m)
}
func (m *PriceType) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceType.DiscardUnknown(m)
}

var xxx_messageInfo_PriceType proto.InternalMessageInfo

func (m *PriceType) GetName() PriceType_Name {
	if m != nil {
		return m.Name
	}
	return PriceType_UNKNOWN
}

type OpenType struct {
	Name                 OpenType_Name `protobuf:"varint,1,opt,name=name,proto3,enum=protos.OpenType_Name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OpenType) Reset()         { *m = OpenType{} }
func (m *OpenType) String() string { return proto.CompactTextString(m) }
func (*OpenType) ProtoMessage()    {}
func (*OpenType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{2}
}

func (m *OpenType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenType.Unmarshal(m, b)
}
func (m *OpenType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenType.Marshal(b, m, deterministic)
}
func (m *OpenType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenType.Merge(m, src)
}
func (m *OpenType) XXX_Size() int {
	return xxx_messageInfo_OpenType.Size(m)
}
func (m *OpenType) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenType.DiscardUnknown(m)
}

var xxx_messageInfo_OpenType proto.InternalMessageInfo

func (m *OpenType) GetName() OpenType_Name {
	if m != nil {
		return m.Name
	}
	return OpenType_UNKNOWN
}

type Rule struct {
	Indicator            *Rule_Indicator `protobuf:"bytes,1,opt,name=indicator,proto3" json:"indicator,omitempty"`
	PriceType            PriceType_Name  `protobuf:"varint,2,opt,name=price_type,json=priceType,proto3,enum=protos.PriceType_Name" json:"price_type,omitempty"`
	OpenType             OpenType_Name   `protobuf:"varint,3,opt,name=open_type,json=openType,proto3,enum=protos.OpenType_Name" json:"open_type,omitempty"`
	PeriodNanoseconds    int64           `protobuf:"varint,4,opt,name=period_nanoseconds,json=periodNanoseconds,proto3" json:"period_nanoseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetIndicator() *Rule_Indicator {
	if m != nil {
		return m.Indicator
	}
	return nil
}

func (m *Rule) GetPriceType() PriceType_Name {
	if m != nil {
		return m.PriceType
	}
	return PriceType_UNKNOWN
}

func (m *Rule) GetOpenType() OpenType_Name {
	if m != nil {
		return m.OpenType
	}
	return OpenType_UNKNOWN
}

func (m *Rule) GetPeriodNanoseconds() int64 {
	if m != nil {
		return m.PeriodNanoseconds
	}
	return 0
}

type Rule_Indicator struct {
	// Types that are valid to be assigned to Condition:
	//	*Rule_Indicator_SimpleMovingAverage_
	//	*Rule_Indicator_RelativeStrengthIndex_
	Condition            isRule_Indicator_Condition `protobuf_oneof:"condition"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Rule_Indicator) Reset()         { *m = Rule_Indicator{} }
func (m *Rule_Indicator) String() string { return proto.CompactTextString(m) }
func (*Rule_Indicator) ProtoMessage()    {}
func (*Rule_Indicator) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3, 0}
}

func (m *Rule_Indicator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule_Indicator.Unmarshal(m, b)
}
func (m *Rule_Indicator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule_Indicator.Marshal(b, m, deterministic)
}
func (m *Rule_Indicator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule_Indicator.Merge(m, src)
}
func (m *Rule_Indicator) XXX_Size() int {
	return xxx_messageInfo_Rule_Indicator.Size(m)
}
func (m *Rule_Indicator) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule_Indicator.DiscardUnknown(m)
}

var xxx_messageInfo_Rule_Indicator proto.InternalMessageInfo

type isRule_Indicator_Condition interface {
	isRule_Indicator_Condition()
}

type Rule_Indicator_SimpleMovingAverage_ struct {
	SimpleMovingAverage *Rule_Indicator_SimpleMovingAverage `protobuf:"bytes,1,opt,name=simple_moving_average,json=simpleMovingAverage,proto3,oneof"`
}

type Rule_Indicator_RelativeStrengthIndex_ struct {
	RelativeStrengthIndex *Rule_Indicator_RelativeStrengthIndex `protobuf:"bytes,2,opt,name=relative_strength_index,json=relativeStrengthIndex,proto3,oneof"`
}

func (*Rule_Indicator_SimpleMovingAverage_) isRule_Indicator_Condition() {}

func (*Rule_Indicator_RelativeStrengthIndex_) isRule_Indicator_Condition() {}

func (m *Rule_Indicator) GetCondition() isRule_Indicator_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *Rule_Indicator) GetSimpleMovingAverage() *Rule_Indicator_SimpleMovingAverage {
	if x, ok := m.GetCondition().(*Rule_Indicator_SimpleMovingAverage_); ok {
		return x.SimpleMovingAverage
	}
	return nil
}

func (m *Rule_Indicator) GetRelativeStrengthIndex() *Rule_Indicator_RelativeStrengthIndex {
	if x, ok := m.GetCondition().(*Rule_Indicator_RelativeStrengthIndex_); ok {
		return x.RelativeStrengthIndex
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Rule_Indicator) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Rule_Indicator_SimpleMovingAverage_)(nil),
		(*Rule_Indicator_RelativeStrengthIndex_)(nil),
	}
}

type Rule_Indicator_SimpleMovingAverage struct {
	Condition            Rule_Indicator_SimpleMovingAverage_Condition `protobuf:"varint,1,opt,name=condition,proto3,enum=protos.Rule_Indicator_SimpleMovingAverage_Condition" json:"condition,omitempty"`
	Period               int64                                        `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *Rule_Indicator_SimpleMovingAverage) Reset()         { *m = Rule_Indicator_SimpleMovingAverage{} }
func (m *Rule_Indicator_SimpleMovingAverage) String() string { return proto.CompactTextString(m) }
func (*Rule_Indicator_SimpleMovingAverage) ProtoMessage()    {}
func (*Rule_Indicator_SimpleMovingAverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3, 0, 0}
}

func (m *Rule_Indicator_SimpleMovingAverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule_Indicator_SimpleMovingAverage.Unmarshal(m, b)
}
func (m *Rule_Indicator_SimpleMovingAverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule_Indicator_SimpleMovingAverage.Marshal(b, m, deterministic)
}
func (m *Rule_Indicator_SimpleMovingAverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule_Indicator_SimpleMovingAverage.Merge(m, src)
}
func (m *Rule_Indicator_SimpleMovingAverage) XXX_Size() int {
	return xxx_messageInfo_Rule_Indicator_SimpleMovingAverage.Size(m)
}
func (m *Rule_Indicator_SimpleMovingAverage) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule_Indicator_SimpleMovingAverage.DiscardUnknown(m)
}

var xxx_messageInfo_Rule_Indicator_SimpleMovingAverage proto.InternalMessageInfo

func (m *Rule_Indicator_SimpleMovingAverage) GetCondition() Rule_Indicator_SimpleMovingAverage_Condition {
	if m != nil {
		return m.Condition
	}
	return Rule_Indicator_SimpleMovingAverage_UNKNOWN
}

func (m *Rule_Indicator_SimpleMovingAverage) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

type Rule_Indicator_RelativeStrengthIndex struct {
	Condition            Rule_Indicator_RelativeStrengthIndex_Condition `protobuf:"varint,1,opt,name=condition,proto3,enum=protos.Rule_Indicator_RelativeStrengthIndex_Condition" json:"condition,omitempty"`
	Period               int64                                          `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	OverBought           int64                                          `protobuf:"varint,3,opt,name=over_bought,json=overBought,proto3" json:"over_bought,omitempty"`
	OverSold             int64                                          `protobuf:"varint,4,opt,name=over_sold,json=overSold,proto3" json:"over_sold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Rule_Indicator_RelativeStrengthIndex) Reset()         { *m = Rule_Indicator_RelativeStrengthIndex{} }
func (m *Rule_Indicator_RelativeStrengthIndex) String() string { return proto.CompactTextString(m) }
func (*Rule_Indicator_RelativeStrengthIndex) ProtoMessage()    {}
func (*Rule_Indicator_RelativeStrengthIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{3, 0, 1}
}

func (m *Rule_Indicator_RelativeStrengthIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule_Indicator_RelativeStrengthIndex.Unmarshal(m, b)
}
func (m *Rule_Indicator_RelativeStrengthIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule_Indicator_RelativeStrengthIndex.Marshal(b, m, deterministic)
}
func (m *Rule_Indicator_RelativeStrengthIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule_Indicator_RelativeStrengthIndex.Merge(m, src)
}
func (m *Rule_Indicator_RelativeStrengthIndex) XXX_Size() int {
	return xxx_messageInfo_Rule_Indicator_RelativeStrengthIndex.Size(m)
}
func (m *Rule_Indicator_RelativeStrengthIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule_Indicator_RelativeStrengthIndex.DiscardUnknown(m)
}

var xxx_messageInfo_Rule_Indicator_RelativeStrengthIndex proto.InternalMessageInfo

func (m *Rule_Indicator_RelativeStrengthIndex) GetCondition() Rule_Indicator_RelativeStrengthIndex_Condition {
	if m != nil {
		return m.Condition
	}
	return Rule_Indicator_RelativeStrengthIndex_UNKNOWN
}

func (m *Rule_Indicator_RelativeStrengthIndex) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Rule_Indicator_RelativeStrengthIndex) GetOverBought() int64 {
	if m != nil {
		return m.OverBought
	}
	return 0
}

func (m *Rule_Indicator_RelativeStrengthIndex) GetOverSold() int64 {
	if m != nil {
		return m.OverSold
	}
	return 0
}

type Status struct {
	Name                 Status_Name `protobuf:"varint,1,opt,name=name,proto3,enum=protos.Status_Name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{4}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetName() Status_Name {
	if m != nil {
		return m.Name
	}
	return Status_UNKNOWN
}

type Direction struct {
	Name                 Direction_Name `protobuf:"varint,1,opt,name=name,proto3,enum=protos.Direction_Name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Direction) Reset()         { *m = Direction{} }
func (m *Direction) String() string { return proto.CompactTextString(m) }
func (*Direction) ProtoMessage()    {}
func (*Direction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{5}
}

func (m *Direction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Direction.Unmarshal(m, b)
}
func (m *Direction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Direction.Marshal(b, m, deterministic)
}
func (m *Direction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Direction.Merge(m, src)
}
func (m *Direction) XXX_Size() int {
	return xxx_messageInfo_Direction.Size(m)
}
func (m *Direction) XXX_DiscardUnknown() {
	xxx_messageInfo_Direction.DiscardUnknown(m)
}

var xxx_messageInfo_Direction proto.InternalMessageInfo

func (m *Direction) GetName() Direction_Name {
	if m != nil {
		return m.Name
	}
	return Direction_UNKNOWN
}

type Position struct {
	Direction            Direction_Name       `protobuf:"varint,1,opt,name=direction,proto3,enum=protos.Direction_Name" json:"direction,omitempty"`
	OpenPrice            int64                `protobuf:"varint,2,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	ClosePrice           int64                `protobuf:"varint,3,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	OpenTime             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	Id                   string               `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{6}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetDirection() Direction_Name {
	if m != nil {
		return m.Direction
	}
	return Direction_UNKNOWN
}

func (m *Position) GetOpenPrice() int64 {
	if m != nil {
		return m.OpenPrice
	}
	return 0
}

func (m *Position) GetClosePrice() int64 {
	if m != nil {
		return m.ClosePrice
	}
	return 0
}

func (m *Position) GetOpenTime() *timestamp.Timestamp {
	if m != nil {
		return m.OpenTime
	}
	return nil
}

func (m *Position) GetCloseTime() *timestamp.Timestamp {
	if m != nil {
		return m.CloseTime
	}
	return nil
}

func (m *Position) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Symbol struct {
	Name                 Symbol_Name `protobuf:"varint,1,opt,name=name,proto3,enum=protos.Symbol_Name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Symbol) Reset()         { *m = Symbol{} }
func (m *Symbol) String() string { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()    {}
func (*Symbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{7}
}

func (m *Symbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Symbol.Unmarshal(m, b)
}
func (m *Symbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Symbol.Marshal(b, m, deterministic)
}
func (m *Symbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Symbol.Merge(m, src)
}
func (m *Symbol) XXX_Size() int {
	return xxx_messageInfo_Symbol.Size(m)
}
func (m *Symbol) XXX_DiscardUnknown() {
	xxx_messageInfo_Symbol.DiscardUnknown(m)
}

var xxx_messageInfo_Symbol proto.InternalMessageInfo

func (m *Symbol) GetName() Symbol_Name {
	if m != nil {
		return m.Name
	}
	return Symbol_UNKNOWN
}

type Strategy struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EntryRules           []*Rule              `protobuf:"bytes,2,rep,name=entry_rules,json=entryRules,proto3" json:"entry_rules,omitempty"`
	ExitRules            []*Rule              `protobuf:"bytes,3,rep,name=exit_rules,json=exitRules,proto3" json:"exit_rules,omitempty"`
	TradeSize            int64                `protobuf:"varint,4,opt,name=trade_size,json=tradeSize,proto3" json:"trade_size,omitempty"`
	TakeProfit           int64                `protobuf:"varint,5,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	StopLoss             int64                `protobuf:"varint,6,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	Status               Status_Name          `protobuf:"varint,7,opt,name=status,proto3,enum=protos.Status_Name" json:"status,omitempty"`
	Id                   string               `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Symbol               Symbol_Name          `protobuf:"varint,9,opt,name=symbol,proto3,enum=protos.Symbol_Name" json:"symbol,omitempty"`
	Positions            []*Position          `protobuf:"bytes,10,rep,name=positions,proto3" json:"positions,omitempty"`
	LastEvaluated        *timestamp.Timestamp `protobuf:"bytes,11,opt,name=last_evaluated,json=lastEvaluated,proto3" json:"last_evaluated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Strategy) Reset()         { *m = Strategy{} }
func (m *Strategy) String() string { return proto.CompactTextString(m) }
func (*Strategy) ProtoMessage()    {}
func (*Strategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{8}
}

func (m *Strategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strategy.Unmarshal(m, b)
}
func (m *Strategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strategy.Marshal(b, m, deterministic)
}
func (m *Strategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strategy.Merge(m, src)
}
func (m *Strategy) XXX_Size() int {
	return xxx_messageInfo_Strategy.Size(m)
}
func (m *Strategy) XXX_DiscardUnknown() {
	xxx_messageInfo_Strategy.DiscardUnknown(m)
}

var xxx_messageInfo_Strategy proto.InternalMessageInfo

func (m *Strategy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Strategy) GetEntryRules() []*Rule {
	if m != nil {
		return m.EntryRules
	}
	return nil
}

func (m *Strategy) GetExitRules() []*Rule {
	if m != nil {
		return m.ExitRules
	}
	return nil
}

func (m *Strategy) GetTradeSize() int64 {
	if m != nil {
		return m.TradeSize
	}
	return 0
}

func (m *Strategy) GetTakeProfit() int64 {
	if m != nil {
		return m.TakeProfit
	}
	return 0
}

func (m *Strategy) GetStopLoss() int64 {
	if m != nil {
		return m.StopLoss
	}
	return 0
}

func (m *Strategy) GetStatus() Status_Name {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Strategy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Strategy) GetSymbol() Symbol_Name {
	if m != nil {
		return m.Symbol
	}
	return Symbol_UNKNOWN
}

func (m *Strategy) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *Strategy) GetLastEvaluated() *timestamp.Timestamp {
	if m != nil {
		return m.LastEvaluated
	}
	return nil
}

type CreateStrategyRequest struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateStrategyRequest) Reset()         { *m = CreateStrategyRequest{} }
func (m *CreateStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStrategyRequest) ProtoMessage()    {}
func (*CreateStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{9}
}

func (m *CreateStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStrategyRequest.Unmarshal(m, b)
}
func (m *CreateStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStrategyRequest.Marshal(b, m, deterministic)
}
func (m *CreateStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStrategyRequest.Merge(m, src)
}
func (m *CreateStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStrategyRequest.Size(m)
}
func (m *CreateStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStrategyRequest proto.InternalMessageInfo

func (m *CreateStrategyRequest) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type CreateStrategyResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStrategyResponse) Reset()         { *m = CreateStrategyResponse{} }
func (m *CreateStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStrategyResponse) ProtoMessage()    {}
func (*CreateStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{10}
}

func (m *CreateStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStrategyResponse.Unmarshal(m, b)
}
func (m *CreateStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStrategyResponse.Marshal(b, m, deterministic)
}
func (m *CreateStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStrategyResponse.Merge(m, src)
}
func (m *CreateStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStrategyResponse.Size(m)
}
func (m *CreateStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStrategyResponse proto.InternalMessageInfo

func (m *CreateStrategyResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateStrategyRequest struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateStrategyRequest) Reset()         { *m = UpdateStrategyRequest{} }
func (m *UpdateStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStrategyRequest) ProtoMessage()    {}
func (*UpdateStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{11}
}

func (m *UpdateStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStrategyRequest.Unmarshal(m, b)
}
func (m *UpdateStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStrategyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStrategyRequest.Merge(m, src)
}
func (m *UpdateStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStrategyRequest.Size(m)
}
func (m *UpdateStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStrategyRequest proto.InternalMessageInfo

func (m *UpdateStrategyRequest) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type UpdateStrategyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStrategyResponse) Reset()         { *m = UpdateStrategyResponse{} }
func (m *UpdateStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStrategyResponse) ProtoMessage()    {}
func (*UpdateStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{12}
}

func (m *UpdateStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStrategyResponse.Unmarshal(m, b)
}
func (m *UpdateStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStrategyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStrategyResponse.Merge(m, src)
}
func (m *UpdateStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStrategyResponse.Size(m)
}
func (m *UpdateStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStrategyResponse proto.InternalMessageInfo

type DeleteStrategyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStrategyRequest) Reset()         { *m = DeleteStrategyRequest{} }
func (m *DeleteStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStrategyRequest) ProtoMessage()    {}
func (*DeleteStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{13}
}

func (m *DeleteStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStrategyRequest.Unmarshal(m, b)
}
func (m *DeleteStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStrategyRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStrategyRequest.Merge(m, src)
}
func (m *DeleteStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStrategyRequest.Size(m)
}
func (m *DeleteStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStrategyRequest proto.InternalMessageInfo

func (m *DeleteStrategyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteStrategyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStrategyResponse) Reset()         { *m = DeleteStrategyResponse{} }
func (m *DeleteStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStrategyResponse) ProtoMessage()    {}
func (*DeleteStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{14}
}

func (m *DeleteStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStrategyResponse.Unmarshal(m, b)
}
func (m *DeleteStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStrategyResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStrategyResponse.Merge(m, src)
}
func (m *DeleteStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStrategyResponse.Size(m)
}
func (m *DeleteStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStrategyResponse proto.InternalMessageInfo

type ListStrategiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStrategiesRequest) Reset()         { *m = ListStrategiesRequest{} }
func (m *ListStrategiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListStrategiesRequest) ProtoMessage()    {}
func (*ListStrategiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{15}
}

func (m *ListStrategiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStrategiesRequest.Unmarshal(m, b)
}
func (m *ListStrategiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStrategiesRequest.Marshal(b, m, deterministic)
}
func (m *ListStrategiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStrategiesRequest.Merge(m, src)
}
func (m *ListStrategiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListStrategiesRequest.Size(m)
}
func (m *ListStrategiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStrategiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStrategiesRequest proto.InternalMessageInfo

type ListStrategiesResponse struct {
	Strategies           []*Strategy `protobuf:"bytes,1,rep,name=strategies,proto3" json:"strategies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListStrategiesResponse) Reset()         { *m = ListStrategiesResponse{} }
func (m *ListStrategiesResponse) String() string { return proto.CompactTextString(m) }
func (*ListStrategiesResponse) ProtoMessage()    {}
func (*ListStrategiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{16}
}

func (m *ListStrategiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStrategiesResponse.Unmarshal(m, b)
}
func (m *ListStrategiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStrategiesResponse.Marshal(b, m, deterministic)
}
func (m *ListStrategiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStrategiesResponse.Merge(m, src)
}
func (m *ListStrategiesResponse) XXX_Size() int {
	return xxx_messageInfo_ListStrategiesResponse.Size(m)
}
func (m *ListStrategiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStrategiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStrategiesResponse proto.InternalMessageInfo

func (m *ListStrategiesResponse) GetStrategies() []*Strategy {
	if m != nil {
		return m.Strategies
	}
	return nil
}

type EvaulateStrategyRequest struct {
	Strategy             *Strategy      `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Candlesticks         []*Candlestick `protobuf:"bytes,2,rep,name=candlesticks,proto3" json:"candlesticks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EvaulateStrategyRequest) Reset()         { *m = EvaulateStrategyRequest{} }
func (m *EvaulateStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*EvaulateStrategyRequest) ProtoMessage()    {}
func (*EvaulateStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{17}
}

func (m *EvaulateStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaulateStrategyRequest.Unmarshal(m, b)
}
func (m *EvaulateStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaulateStrategyRequest.Marshal(b, m, deterministic)
}
func (m *EvaulateStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaulateStrategyRequest.Merge(m, src)
}
func (m *EvaulateStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_EvaulateStrategyRequest.Size(m)
}
func (m *EvaulateStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaulateStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvaulateStrategyRequest proto.InternalMessageInfo

func (m *EvaulateStrategyRequest) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *EvaulateStrategyRequest) GetCandlesticks() []*Candlestick {
	if m != nil {
		return m.Candlesticks
	}
	return nil
}

type EvaluateStrategyResponse struct {
	Action               *EvaluateStrategyResponse_Action `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *EvaluateStrategyResponse) Reset()         { *m = EvaluateStrategyResponse{} }
func (m *EvaluateStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*EvaluateStrategyResponse) ProtoMessage()    {}
func (*EvaluateStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{18}
}

func (m *EvaluateStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateStrategyResponse.Unmarshal(m, b)
}
func (m *EvaluateStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateStrategyResponse.Marshal(b, m, deterministic)
}
func (m *EvaluateStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateStrategyResponse.Merge(m, src)
}
func (m *EvaluateStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_EvaluateStrategyResponse.Size(m)
}
func (m *EvaluateStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateStrategyResponse proto.InternalMessageInfo

func (m *EvaluateStrategyResponse) GetAction() *EvaluateStrategyResponse_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type EvaluateStrategyResponse_Action struct {
	// Types that are valid to be assigned to Action:
	//	*EvaluateStrategyResponse_Action_OpenPosition_
	//	*EvaluateStrategyResponse_Action_ClosePosition_
	Action               isEvaluateStrategyResponse_Action_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *EvaluateStrategyResponse_Action) Reset()         { *m = EvaluateStrategyResponse_Action{} }
func (m *EvaluateStrategyResponse_Action) String() string { return proto.CompactTextString(m) }
func (*EvaluateStrategyResponse_Action) ProtoMessage()    {}
func (*EvaluateStrategyResponse_Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{18, 0}
}

func (m *EvaluateStrategyResponse_Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateStrategyResponse_Action.Unmarshal(m, b)
}
func (m *EvaluateStrategyResponse_Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateStrategyResponse_Action.Marshal(b, m, deterministic)
}
func (m *EvaluateStrategyResponse_Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateStrategyResponse_Action.Merge(m, src)
}
func (m *EvaluateStrategyResponse_Action) XXX_Size() int {
	return xxx_messageInfo_EvaluateStrategyResponse_Action.Size(m)
}
func (m *EvaluateStrategyResponse_Action) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateStrategyResponse_Action.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateStrategyResponse_Action proto.InternalMessageInfo

type isEvaluateStrategyResponse_Action_Action interface {
	isEvaluateStrategyResponse_Action_Action()
}

type EvaluateStrategyResponse_Action_OpenPosition_ struct {
	OpenPosition *EvaluateStrategyResponse_Action_OpenPosition `protobuf:"bytes,1,opt,name=open_position,json=openPosition,proto3,oneof"`
}

type EvaluateStrategyResponse_Action_ClosePosition_ struct {
	ClosePosition *EvaluateStrategyResponse_Action_ClosePosition `protobuf:"bytes,2,opt,name=close_position,json=closePosition,proto3,oneof"`
}

func (*EvaluateStrategyResponse_Action_OpenPosition_) isEvaluateStrategyResponse_Action_Action() {}

func (*EvaluateStrategyResponse_Action_ClosePosition_) isEvaluateStrategyResponse_Action_Action() {}

func (m *EvaluateStrategyResponse_Action) GetAction() isEvaluateStrategyResponse_Action_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *EvaluateStrategyResponse_Action) GetOpenPosition() *EvaluateStrategyResponse_Action_OpenPosition {
	if x, ok := m.GetAction().(*EvaluateStrategyResponse_Action_OpenPosition_); ok {
		return x.OpenPosition
	}
	return nil
}

func (m *EvaluateStrategyResponse_Action) GetClosePosition() *EvaluateStrategyResponse_Action_ClosePosition {
	if x, ok := m.GetAction().(*EvaluateStrategyResponse_Action_ClosePosition_); ok {
		return x.ClosePosition
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EvaluateStrategyResponse_Action) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EvaluateStrategyResponse_Action_OpenPosition_)(nil),
		(*EvaluateStrategyResponse_Action_ClosePosition_)(nil),
	}
}

type EvaluateStrategyResponse_Action_OpenPosition struct {
	Direction            Direction_Name `protobuf:"varint,1,opt,name=direction,proto3,enum=protos.Direction_Name" json:"direction,omitempty"`
	Price                int64          `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EvaluateStrategyResponse_Action_OpenPosition) Reset() {
	*m = EvaluateStrategyResponse_Action_OpenPosition{}
}
func (m *EvaluateStrategyResponse_Action_OpenPosition) String() string {
	return proto.CompactTextString(m)
}
func (*EvaluateStrategyResponse_Action_OpenPosition) ProtoMessage() {}
func (*EvaluateStrategyResponse_Action_OpenPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{18, 0, 0}
}

func (m *EvaluateStrategyResponse_Action_OpenPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateStrategyResponse_Action_OpenPosition.Unmarshal(m, b)
}
func (m *EvaluateStrategyResponse_Action_OpenPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateStrategyResponse_Action_OpenPosition.Marshal(b, m, deterministic)
}
func (m *EvaluateStrategyResponse_Action_OpenPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateStrategyResponse_Action_OpenPosition.Merge(m, src)
}
func (m *EvaluateStrategyResponse_Action_OpenPosition) XXX_Size() int {
	return xxx_messageInfo_EvaluateStrategyResponse_Action_OpenPosition.Size(m)
}
func (m *EvaluateStrategyResponse_Action_OpenPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateStrategyResponse_Action_OpenPosition.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateStrategyResponse_Action_OpenPosition proto.InternalMessageInfo

func (m *EvaluateStrategyResponse_Action_OpenPosition) GetDirection() Direction_Name {
	if m != nil {
		return m.Direction
	}
	return Direction_UNKNOWN
}

func (m *EvaluateStrategyResponse_Action_OpenPosition) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type EvaluateStrategyResponse_Action_ClosePosition struct {
	Price                int64    `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvaluateStrategyResponse_Action_ClosePosition) Reset() {
	*m = EvaluateStrategyResponse_Action_ClosePosition{}
}
func (m *EvaluateStrategyResponse_Action_ClosePosition) String() string {
	return proto.CompactTextString(m)
}
func (*EvaluateStrategyResponse_Action_ClosePosition) ProtoMessage() {}
func (*EvaluateStrategyResponse_Action_ClosePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{18, 0, 1}
}

func (m *EvaluateStrategyResponse_Action_ClosePosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateStrategyResponse_Action_ClosePosition.Unmarshal(m, b)
}
func (m *EvaluateStrategyResponse_Action_ClosePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateStrategyResponse_Action_ClosePosition.Marshal(b, m, deterministic)
}
func (m *EvaluateStrategyResponse_Action_ClosePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateStrategyResponse_Action_ClosePosition.Merge(m, src)
}
func (m *EvaluateStrategyResponse_Action_ClosePosition) XXX_Size() int {
	return xxx_messageInfo_EvaluateStrategyResponse_Action_ClosePosition.Size(m)
}
func (m *EvaluateStrategyResponse_Action_ClosePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateStrategyResponse_Action_ClosePosition.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateStrategyResponse_Action_ClosePosition proto.InternalMessageInfo

func (m *EvaluateStrategyResponse_Action_ClosePosition) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetPriceHistoryRequest struct {
	Symbol               Symbol_Name `protobuf:"varint,1,opt,name=symbol,proto3,enum=protos.Symbol_Name" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPriceHistoryRequest) Reset()         { *m = GetPriceHistoryRequest{} }
func (m *GetPriceHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetPriceHistoryRequest) ProtoMessage()    {}
func (*GetPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{19}
}

func (m *GetPriceHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceHistoryRequest.Unmarshal(m, b)
}
func (m *GetPriceHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetPriceHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceHistoryRequest.Merge(m, src)
}
func (m *GetPriceHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetPriceHistoryRequest.Size(m)
}
func (m *GetPriceHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceHistoryRequest proto.InternalMessageInfo

func (m *GetPriceHistoryRequest) GetSymbol() Symbol_Name {
	if m != nil {
		return m.Symbol
	}
	return Symbol_UNKNOWN
}

type GetPriceHistoryResponse struct {
	Candlesticks         []*Candlestick `protobuf:"bytes,1,rep,name=candlesticks,proto3" json:"candlesticks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPriceHistoryResponse) Reset()         { *m = GetPriceHistoryResponse{} }
func (m *GetPriceHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetPriceHistoryResponse) ProtoMessage()    {}
func (*GetPriceHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{20}
}

func (m *GetPriceHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceHistoryResponse.Unmarshal(m, b)
}
func (m *GetPriceHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetPriceHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceHistoryResponse.Merge(m, src)
}
func (m *GetPriceHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetPriceHistoryResponse.Size(m)
}
func (m *GetPriceHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceHistoryResponse proto.InternalMessageInfo

func (m *GetPriceHistoryResponse) GetCandlesticks() []*Candlestick {
	if m != nil {
		return m.Candlesticks
	}
	return nil
}

type OpenPositionRequest struct {
	Direction            Direction_Name `protobuf:"varint,1,opt,name=direction,proto3,enum=protos.Direction_Name" json:"direction,omitempty"`
	Price                int64          `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OpenPositionRequest) Reset()         { *m = OpenPositionRequest{} }
func (m *OpenPositionRequest) String() string { return proto.CompactTextString(m) }
func (*OpenPositionRequest) ProtoMessage()    {}
func (*OpenPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{21}
}

func (m *OpenPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenPositionRequest.Unmarshal(m, b)
}
func (m *OpenPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenPositionRequest.Marshal(b, m, deterministic)
}
func (m *OpenPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenPositionRequest.Merge(m, src)
}
func (m *OpenPositionRequest) XXX_Size() int {
	return xxx_messageInfo_OpenPositionRequest.Size(m)
}
func (m *OpenPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenPositionRequest proto.InternalMessageInfo

func (m *OpenPositionRequest) GetDirection() Direction_Name {
	if m != nil {
		return m.Direction
	}
	return Direction_UNKNOWN
}

func (m *OpenPositionRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type OpenPositionResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecutionTime        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	ExecutionPrice       int64                `protobuf:"varint,3,opt,name=execution_price,json=executionPrice,proto3" json:"execution_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OpenPositionResponse) Reset()         { *m = OpenPositionResponse{} }
func (m *OpenPositionResponse) String() string { return proto.CompactTextString(m) }
func (*OpenPositionResponse) ProtoMessage()    {}
func (*OpenPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{22}
}

func (m *OpenPositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenPositionResponse.Unmarshal(m, b)
}
func (m *OpenPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenPositionResponse.Marshal(b, m, deterministic)
}
func (m *OpenPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenPositionResponse.Merge(m, src)
}
func (m *OpenPositionResponse) XXX_Size() int {
	return xxx_messageInfo_OpenPositionResponse.Size(m)
}
func (m *OpenPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenPositionResponse proto.InternalMessageInfo

func (m *OpenPositionResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenPositionResponse) GetExecutionTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExecutionTime
	}
	return nil
}

func (m *OpenPositionResponse) GetExecutionPrice() int64 {
	if m != nil {
		return m.ExecutionPrice
	}
	return 0
}

type ClosePositionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClosePositionRequest) Reset()         { *m = ClosePositionRequest{} }
func (m *ClosePositionRequest) String() string { return proto.CompactTextString(m) }
func (*ClosePositionRequest) ProtoMessage()    {}
func (*ClosePositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{23}
}

func (m *ClosePositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosePositionRequest.Unmarshal(m, b)
}
func (m *ClosePositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosePositionRequest.Marshal(b, m, deterministic)
}
func (m *ClosePositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosePositionRequest.Merge(m, src)
}
func (m *ClosePositionRequest) XXX_Size() int {
	return xxx_messageInfo_ClosePositionRequest.Size(m)
}
func (m *ClosePositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosePositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClosePositionRequest proto.InternalMessageInfo

func (m *ClosePositionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClosePositionRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ClosePositionResponse struct {
	ExecutionTime        *timestamp.Timestamp `protobuf:"bytes,1,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	ExecutionPrice       int64                `protobuf:"varint,2,opt,name=execution_price,json=executionPrice,proto3" json:"execution_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClosePositionResponse) Reset()         { *m = ClosePositionResponse{} }
func (m *ClosePositionResponse) String() string { return proto.CompactTextString(m) }
func (*ClosePositionResponse) ProtoMessage()    {}
func (*ClosePositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da3cbeb884d181c, []int{24}
}

func (m *ClosePositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosePositionResponse.Unmarshal(m, b)
}
func (m *ClosePositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosePositionResponse.Marshal(b, m, deterministic)
}
func (m *ClosePositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosePositionResponse.Merge(m, src)
}
func (m *ClosePositionResponse) XXX_Size() int {
	return xxx_messageInfo_ClosePositionResponse.Size(m)
}
func (m *ClosePositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosePositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClosePositionResponse proto.InternalMessageInfo

func (m *ClosePositionResponse) GetExecutionTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExecutionTime
	}
	return nil
}

func (m *ClosePositionResponse) GetExecutionPrice() int64 {
	if m != nil {
		return m.ExecutionPrice
	}
	return 0
}

func init() {
	proto.RegisterEnum("protos.PriceType_Name", PriceType_Name_name, PriceType_Name_value)
	proto.RegisterEnum("protos.OpenType_Name", OpenType_Name_name, OpenType_Name_value)
	proto.RegisterEnum("protos.Rule_Indicator_SimpleMovingAverage_Condition", Rule_Indicator_SimpleMovingAverage_Condition_name, Rule_Indicator_SimpleMovingAverage_Condition_value)
	proto.RegisterEnum("protos.Rule_Indicator_RelativeStrengthIndex_Condition", Rule_Indicator_RelativeStrengthIndex_Condition_name, Rule_Indicator_RelativeStrengthIndex_Condition_value)
	proto.RegisterEnum("protos.Status_Name", Status_Name_name, Status_Name_value)
	proto.RegisterEnum("protos.Direction_Name", Direction_Name_name, Direction_Name_value)
	proto.RegisterEnum("protos.Symbol_Name", Symbol_Name_name, Symbol_Name_value)
	proto.RegisterType((*Candlestick)(nil), "protos.Candlestick")
	proto.RegisterType((*PriceType)(nil), "protos.PriceType")
	proto.RegisterType((*OpenType)(nil), "protos.OpenType")
	proto.RegisterType((*Rule)(nil), "protos.Rule")
	proto.RegisterType((*Rule_Indicator)(nil), "protos.Rule.Indicator")
	proto.RegisterType((*Rule_Indicator_SimpleMovingAverage)(nil), "protos.Rule.Indicator.SimpleMovingAverage")
	proto.RegisterType((*Rule_Indicator_RelativeStrengthIndex)(nil), "protos.Rule.Indicator.RelativeStrengthIndex")
	proto.RegisterType((*Status)(nil), "protos.Status")
	proto.RegisterType((*Direction)(nil), "protos.Direction")
	proto.RegisterType((*Position)(nil), "protos.Position")
	proto.RegisterType((*Symbol)(nil), "protos.Symbol")
	proto.RegisterType((*Strategy)(nil), "protos.Strategy")
	proto.RegisterType((*CreateStrategyRequest)(nil), "protos.CreateStrategyRequest")
	proto.RegisterType((*CreateStrategyResponse)(nil), "protos.CreateStrategyResponse")
	proto.RegisterType((*UpdateStrategyRequest)(nil), "protos.UpdateStrategyRequest")
	proto.RegisterType((*UpdateStrategyResponse)(nil), "protos.UpdateStrategyResponse")
	proto.RegisterType((*DeleteStrategyRequest)(nil), "protos.DeleteStrategyRequest")
	proto.RegisterType((*DeleteStrategyResponse)(nil), "protos.DeleteStrategyResponse")
	proto.RegisterType((*ListStrategiesRequest)(nil), "protos.ListStrategiesRequest")
	proto.RegisterType((*ListStrategiesResponse)(nil), "protos.ListStrategiesResponse")
	proto.RegisterType((*EvaulateStrategyRequest)(nil), "protos.EvaulateStrategyRequest")
	proto.RegisterType((*EvaluateStrategyResponse)(nil), "protos.EvaluateStrategyResponse")
	proto.RegisterType((*EvaluateStrategyResponse_Action)(nil), "protos.EvaluateStrategyResponse.Action")
	proto.RegisterType((*EvaluateStrategyResponse_Action_OpenPosition)(nil), "protos.EvaluateStrategyResponse.Action.OpenPosition")
	proto.RegisterType((*EvaluateStrategyResponse_Action_ClosePosition)(nil), "protos.EvaluateStrategyResponse.Action.ClosePosition")
	proto.RegisterType((*GetPriceHistoryRequest)(nil), "protos.GetPriceHistoryRequest")
	proto.RegisterType((*GetPriceHistoryResponse)(nil), "protos.GetPriceHistoryResponse")
	proto.RegisterType((*OpenPositionRequest)(nil), "protos.OpenPositionRequest")
	proto.RegisterType((*OpenPositionResponse)(nil), "protos.OpenPositionResponse")
	proto.RegisterType((*ClosePositionRequest)(nil), "protos.ClosePositionRequest")
	proto.RegisterType((*ClosePositionResponse)(nil), "protos.ClosePositionResponse")
}

func init() { proto.RegisterFile("protos.proto", fileDescriptor_5da3cbeb884d181c) }

var fileDescriptor_5da3cbeb884d181c = []byte{
	// 1587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0xdb, 0x56,
	0x12, 0x36, 0x29, 0x5b, 0x16, 0x47, 0xb6, 0xa3, 0x1c, 0x5b, 0x32, 0x57, 0x59, 0xaf, 0x0d, 0x02,
	0xbb, 0xf6, 0x66, 0x13, 0x79, 0xa1, 0x75, 0x36, 0xbb, 0x40, 0x81, 0x42, 0xb2, 0x58, 0xdb, 0xad,
	0x22, 0x19, 0x94, 0x95, 0xa0, 0x29, 0x50, 0x86, 0x96, 0x4e, 0x64, 0xc2, 0x14, 0xa9, 0x92, 0x47,
	0x4e, 0x9c, 0xab, 0x02, 0x2d, 0xfa, 0x00, 0x79, 0x8a, 0x5e, 0xb6, 0x40, 0x5f, 0x22, 0x40, 0x6f,
	0xda, 0x8b, 0xbe, 0x4d, 0x81, 0xe2, 0xfc, 0xf0, 0x47, 0x32, 0x15, 0x3b, 0x4d, 0xae, 0xcc, 0x33,
	0xf3, 0xcd, 0x0c, 0xe7, 0xe7, 0x7c, 0x43, 0x0b, 0x96, 0x46, 0xbe, 0x47, 0xbc, 0xa0, 0xc2, 0xfe,
	0xa0, 0x2c, 0x3f, 0x95, 0x37, 0x07, 0x9e, 0x37, 0x70, 0xf0, 0x2e, 0x3b, 0x9e, 0x8e, 0x9f, 0xef,
	0x12, 0x7b, 0x88, 0x03, 0x62, 0x0d, 0x47, 0x1c, 0xa8, 0xfd, 0x28, 0x41, 0x7e, 0xdf, 0x72, 0xfb,
	0x0e, 0x0e, 0x88, 0xdd, 0x3b, 0x47, 0xff, 0x03, 0x25, 0x82, 0xa8, 0xd2, 0x96, 0xb4, 0x93, 0xaf,
	0x96, 0x2b, 0xdc, 0x49, 0x25, 0x74, 0x52, 0x39, 0x09, 0x11, 0x46, 0x0c, 0x46, 0x2a, 0x2c, 0xf6,
	0xc6, 0xbe, 0x8f, 0x5d, 0xa2, 0xca, 0x5b, 0xd2, 0x4e, 0xc6, 0x08, 0x8f, 0xa8, 0x00, 0x19, 0xc7,
	0x7b, 0xa1, 0x66, 0x98, 0x94, 0x3e, 0x22, 0x04, 0xf3, 0x67, 0xf6, 0xe0, 0x4c, 0x9d, 0x67, 0x22,
	0xf6, 0x4c, 0x65, 0xde, 0x08, 0xbb, 0xea, 0x02, 0x97, 0xd1, 0x67, 0xb4, 0x06, 0x0b, 0x3d, 0xc7,
	0x0b, 0xb0, 0x9a, 0x65, 0x42, 0x7e, 0xd0, 0x2c, 0x50, 0x8e, 0x7d, 0xbb, 0x87, 0x4f, 0x2e, 0x47,
	0x18, 0xdd, 0x85, 0x79, 0xd7, 0x1a, 0x62, 0xf6, 0xae, 0x2b, 0xd5, 0x52, 0x45, 0x94, 0x21, 0x02,
	0x54, 0x5a, 0xd6, 0x10, 0x1b, 0x0c, 0xa3, 0xed, 0xc0, 0x3c, 0x3d, 0xa1, 0x3c, 0x2c, 0x76, 0x5b,
	0x9f, 0xb5, 0xda, 0x4f, 0x5a, 0x85, 0x39, 0x94, 0x83, 0xf9, 0xf6, 0xb1, 0xde, 0x2a, 0x48, 0x48,
	0x81, 0x85, 0xfd, 0x66, 0xbb, 0xa3, 0x17, 0x64, 0xad, 0x07, 0xb9, 0xf6, 0x08, 0xbb, 0x2c, 0xc2,
	0x3f, 0x27, 0x22, 0x14, 0xc3, 0x08, 0xa1, 0x3e, 0x19, 0xe0, 0x5e, 0x5a, 0x00, 0x80, 0x6c, 0xab,
	0x6d, 0x3c, 0xaa, 0x35, 0x0b, 0x12, 0x55, 0x18, 0xfa, 0x63, 0xdd, 0x60, 0x41, 0x7e, 0x5b, 0x84,
	0x79, 0x63, 0xec, 0x60, 0xb4, 0x07, 0x8a, 0xed, 0xf6, 0xed, 0x9e, 0x45, 0x3c, 0x5f, 0x14, 0x3d,
	0x4a, 0x84, 0x02, 0x2a, 0x47, 0xa1, 0xd6, 0x88, 0x81, 0xe8, 0x01, 0xc0, 0x88, 0x66, 0x69, 0x92,
	0xcb, 0x11, 0x66, 0x35, 0x9f, 0x9d, 0xbf, 0x32, 0x8a, 0x0a, 0x56, 0x05, 0x85, 0xd6, 0x96, 0x5b,
	0x65, 0xde, 0x96, 0x53, 0xce, 0x0b, 0x4b, 0x70, 0x1f, 0xd0, 0x08, 0xfb, 0xb6, 0xd7, 0x37, 0x5d,
	0xcb, 0xf5, 0x02, 0xdc, 0xf3, 0xdc, 0x7e, 0x20, 0xba, 0x77, 0x9b, 0x6b, 0x5a, 0xb1, 0xa2, 0xfc,
	0xfb, 0x02, 0x28, 0xd1, 0x2b, 0xa3, 0x67, 0x50, 0x0c, 0xec, 0xe1, 0xc8, 0xc1, 0xe6, 0xd0, 0xbb,
	0xb0, 0xdd, 0x81, 0x69, 0x5d, 0x60, 0xdf, 0x1a, 0x60, 0x91, 0xe9, 0xdd, 0xf4, 0x4c, 0x2b, 0x1d,
	0x66, 0xf3, 0x88, 0x99, 0xd4, 0xb8, 0xc5, 0xe1, 0x9c, 0xb1, 0x1a, 0x5c, 0x15, 0xa3, 0xe7, 0xb0,
	0xee, 0x63, 0xc7, 0x22, 0xf6, 0x05, 0x36, 0x03, 0xe2, 0x63, 0x77, 0x40, 0xce, 0x4c, 0xdb, 0xed,
	0xe3, 0x97, 0xac, 0x2c, 0xf9, 0xea, 0xbd, 0x19, 0x31, 0x0c, 0x61, 0xd5, 0x11, 0x46, 0x47, 0xd4,
	0xe6, 0x70, 0xce, 0x28, 0xfa, 0x69, 0x8a, 0xf2, 0x1b, 0x09, 0x56, 0x53, 0x5e, 0x0b, 0x19, 0xa0,
	0xd0, 0xc4, 0x6d, 0x62, 0x7b, 0xae, 0x18, 0x93, 0xbd, 0x9b, 0x67, 0x55, 0xd9, 0x0f, 0x6d, 0x8d,
	0xd8, 0x0d, 0x2a, 0x41, 0x96, 0x17, 0x56, 0xdc, 0x26, 0x71, 0xd2, 0x3e, 0x01, 0x25, 0xc2, 0x4f,
	0xce, 0x59, 0x11, 0x6e, 0xd7, 0xea, 0xed, 0xc7, 0xba, 0xd9, 0x39, 0x3a, 0x68, 0xd5, 0x9a, 0x66,
	0xf3, 0xa8, 0xa5, 0x17, 0x24, 0x2a, 0xae, 0xeb, 0xcd, 0xf6, 0x93, 0x09, 0xb1, 0x5c, 0xfe, 0x59,
	0x86, 0x62, 0x6a, 0xfa, 0xe8, 0xe4, 0x6a, 0x36, 0xff, 0x7d, 0x97, 0xfa, 0xbd, 0x53, 0x3e, 0x68,
	0x13, 0xf2, 0xde, 0x05, 0xf6, 0xcd, 0x53, 0x6f, 0x3c, 0x38, 0x23, 0x82, 0x24, 0x80, 0x8a, 0xea,
	0x4c, 0x82, 0xee, 0x80, 0xc2, 0x00, 0x81, 0xe7, 0xf4, 0xc5, 0xc8, 0xe5, 0xa8, 0xa0, 0xe3, 0x39,
	0x7d, 0xed, 0x3b, 0x69, 0x66, 0x39, 0xca, 0x50, 0xe2, 0xe5, 0x68, 0x3f, 0xd6, 0x0d, 0xb3, 0xde,
	0xee, 0x1e, 0x1c, 0x9e, 0x84, 0x35, 0x29, 0x43, 0x89, 0xd7, 0xe4, 0x8a, 0x4e, 0x46, 0x7f, 0x81,
	0x22, 0xb7, 0xeb, 0xb6, 0x1a, 0xba, 0x61, 0x76, 0xda, 0xcd, 0x06, 0x57, 0x65, 0xa8, 0x8a, 0x9b,
	0x4d, 0xab, 0xe6, 0xeb, 0xf9, 0x44, 0xd1, 0x34, 0x13, 0xb2, 0x1d, 0x62, 0x91, 0x71, 0x80, 0xb6,
	0x27, 0xb8, 0x63, 0x35, 0x2c, 0x23, 0xd7, 0x5e, 0xcb, 0x1c, 0x79, 0x58, 0xd4, 0x5b, 0xb5, 0x7a,
	0x53, 0x6f, 0x14, 0x24, 0x4a, 0x23, 0xc7, 0xb5, 0x6e, 0x47, 0x6f, 0x14, 0x64, 0xcd, 0x04, 0xa5,
	0x61, 0xfb, 0xb8, 0xc7, 0xb2, 0x9e, 0xc1, 0x80, 0x11, 0x20, 0x19, 0xe6, 0x1f, 0x69, 0x61, 0x16,
	0x21, 0x53, 0xef, 0x7e, 0x5e, 0x90, 0x28, 0x15, 0x76, 0xf4, 0x66, 0xb3, 0x20, 0x6b, 0xdf, 0xca,
	0x90, 0x3b, 0xf6, 0x02, 0x5e, 0xd6, 0x3d, 0x50, 0xfa, 0xa1, 0xb3, 0x6b, 0xa2, 0xc4, 0x40, 0xb4,
	0x01, 0xc0, 0x78, 0x86, 0x31, 0x8f, 0x68, 0x3a, 0x63, 0x1e, 0x46, 0x4d, 0xb4, 0xef, 0x8c, 0xcd,
	0x85, 0x5e, 0xf4, 0x9d, 0x89, 0x38, 0xe0, 0x61, 0xc8, 0x53, 0xf6, 0x10, 0xb3, 0xbe, 0xbf, 0x7d,
	0x13, 0x71, 0xb2, 0xb2, 0x87, 0x18, 0xfd, 0x1f, 0xb8, 0x1b, 0x6e, 0xb9, 0x70, 0xfd, 0x0e, 0x63,
	0x68, 0x66, 0xba, 0x02, 0xb2, 0xdd, 0x67, 0xcb, 0x46, 0x31, 0x64, 0xbb, 0xaf, 0x3d, 0x83, 0x6c,
	0xe7, 0x72, 0x78, 0xea, 0x39, 0x33, 0x1b, 0xc9, 0xb4, 0xc9, 0x0a, 0xdf, 0x9f, 0xd5, 0xc8, 0xae,
	0x61, 0x76, 0x3b, 0x0d, 0xbe, 0x03, 0xba, 0x9d, 0x86, 0x79, 0x50, 0x3f, 0x2e, 0xc8, 0xda, 0x4f,
	0x19, 0xc8, 0x75, 0x88, 0x6f, 0x11, 0x3c, 0xb8, 0xa4, 0x2b, 0x30, 0x0a, 0xa2, 0x70, 0x7f, 0xe8,
	0x3e, 0xe4, 0xb1, 0x4b, 0xfc, 0x4b, 0xd3, 0x1f, 0x3b, 0x38, 0x50, 0xe5, 0xad, 0xcc, 0x4e, 0xbe,
	0xba, 0x94, 0xbc, 0x8f, 0x06, 0x30, 0x00, 0x7d, 0x0c, 0xd0, 0xbf, 0x00, 0xf0, 0x4b, 0x9b, 0x08,
	0x74, 0x26, 0x05, 0xad, 0x50, 0x3d, 0x07, 0x6f, 0x00, 0x10, 0xdf, 0xea, 0x63, 0x33, 0xb0, 0x5f,
	0x61, 0x71, 0xb7, 0x14, 0x26, 0xe9, 0xd8, 0xaf, 0x58, 0x8b, 0x88, 0x75, 0x4e, 0x3b, 0xe4, 0x3d,
	0xb7, 0x89, 0x58, 0xcc, 0x40, 0x45, 0xc7, 0x4c, 0x42, 0xaf, 0x66, 0x40, 0xbc, 0x91, 0xe9, 0x78,
	0x41, 0x20, 0x56, 0x74, 0x8e, 0x0a, 0x9a, 0x5e, 0x40, 0xdf, 0x24, 0x1b, 0xb0, 0x31, 0x57, 0x17,
	0x67, 0x0f, 0xbf, 0x80, 0x88, 0xc2, 0xe7, 0xc2, 0xc2, 0x33, 0x63, 0x56, 0x5a, 0x55, 0x99, 0x5d,
	0x70, 0x01, 0x41, 0x15, 0x50, 0x46, 0x62, 0x56, 0x03, 0x15, 0x58, 0xca, 0x85, 0x68, 0x0f, 0x0a,
	0x85, 0x11, 0x43, 0x50, 0x0d, 0x56, 0x1c, 0x2b, 0x20, 0x26, 0xbe, 0xb0, 0x9c, 0xb1, 0x45, 0x70,
	0x5f, 0xcd, 0x5f, 0x3b, 0x24, 0xcb, 0xd4, 0x42, 0x0f, 0x0d, 0x34, 0x1d, 0x8a, 0xfb, 0x3e, 0xb6,
	0x08, 0x0e, 0x7b, 0x67, 0xe0, 0xaf, 0xc6, 0x38, 0x20, 0xe8, 0x1e, 0xe4, 0x02, 0x21, 0x12, 0xfb,
	0xad, 0x10, 0xe7, 0x2d, 0xa0, 0x11, 0x42, 0xdb, 0x81, 0xd2, 0xb4, 0x9b, 0x60, 0xe4, 0xb9, 0x41,
	0x38, 0x89, 0x52, 0x34, 0x89, 0x3a, 0x14, 0xbb, 0xa3, 0xfe, 0x7b, 0x07, 0x54, 0xa1, 0x34, 0xed,
	0x86, 0x07, 0xd4, 0xb6, 0xa1, 0xd8, 0xc0, 0x0e, 0xbe, 0x1a, 0x60, 0xfa, 0x4d, 0x54, 0x28, 0x4d,
	0x03, 0x85, 0x8b, 0x75, 0x28, 0x36, 0xed, 0x80, 0x08, 0xb9, 0x8d, 0x03, 0xe1, 0x42, 0xfb, 0x14,
	0x4a, 0xd3, 0x0a, 0x91, 0xe6, 0xbf, 0x01, 0x82, 0x48, 0xaa, 0x4a, 0x93, 0xbd, 0x8b, 0x02, 0x24,
	0x30, 0xda, 0xd7, 0x12, 0xac, 0xeb, 0x17, 0xd6, 0xd8, 0x79, 0xdf, 0x5a, 0xa0, 0x87, 0xb0, 0xd4,
	0x8b, 0xbf, 0x7c, 0xc3, 0xab, 0x15, 0x4d, 0x5a, 0xe2, 0xab, 0xd8, 0x98, 0x00, 0x6a, 0x3f, 0x64,
	0x40, 0x0d, 0x47, 0xe1, 0x4a, 0xe3, 0x3e, 0x86, 0xac, 0x15, 0x33, 0x65, 0xbe, 0xba, 0x1d, 0xfa,
	0x9b, 0x65, 0x51, 0xa9, 0x31, 0xb8, 0x21, 0xcc, 0xca, 0xbf, 0xca, 0x90, 0xe5, 0x22, 0xf4, 0x05,
	0x2c, 0x73, 0x0a, 0x15, 0xa3, 0x2b, 0x5c, 0xee, 0xdd, 0xd0, 0x25, 0xfb, 0x9c, 0x0b, 0x2f, 0xc0,
	0xe1, 0x9c, 0xb1, 0xe4, 0x25, 0xce, 0xe8, 0x4b, 0x58, 0x11, 0x04, 0x1c, 0x7a, 0xe7, 0xdf, 0x4a,
	0x0f, 0x6e, 0xea, 0x7d, 0x9f, 0x71, 0x75, 0xec, 0x7e, 0xb9, 0x97, 0x14, 0x94, 0x9f, 0xc2, 0x52,
	0x32, 0xfe, 0x9f, 0xdc, 0x22, 0x6b, 0xb0, 0x90, 0x5c, 0x20, 0xfc, 0x50, 0xfe, 0x3b, 0x2c, 0x4f,
	0x44, 0x8f, 0x61, 0x52, 0x02, 0x56, 0xcf, 0x85, 0xbd, 0xd0, 0x74, 0x28, 0x1d, 0x60, 0xc2, 0x16,
	0xcb, 0xa1, 0x1d, 0x10, 0xcf, 0x8f, 0x66, 0x26, 0x66, 0x1a, 0xe9, 0x5a, 0xa6, 0xd1, 0x0c, 0x58,
	0xbf, 0xe2, 0x46, 0xf4, 0x7d, 0x7a, 0x9a, 0xa4, 0x9b, 0x4e, 0x93, 0x05, 0xab, 0xc9, 0x3a, 0x85,
	0xef, 0xf5, 0x01, 0xcb, 0xa5, 0xbd, 0x96, 0x60, 0x6d, 0x32, 0x46, 0x3a, 0xcb, 0x50, 0x66, 0xc4,
	0x2f, 0x71, 0x6f, 0x4c, 0x41, 0x7c, 0x7d, 0xca, 0xd7, 0x33, 0x63, 0x64, 0xc1, 0x56, 0xe8, 0x36,
	0xdc, 0x8a, 0x5d, 0x24, 0x77, 0x7b, 0xec, 0x99, 0xd5, 0x4f, 0xfb, 0x08, 0xd6, 0x26, 0x7a, 0x38,
	0x83, 0x6f, 0x66, 0xa4, 0xf4, 0x8d, 0x04, 0xc5, 0x29, 0x73, 0x91, 0xd3, 0xd5, 0x1c, 0xa4, 0x0f,
	0x90, 0x83, 0x9c, 0x96, 0x43, 0xf5, 0x17, 0x19, 0xf2, 0x0d, 0x8b, 0x58, 0x1d, 0xec, 0x5f, 0xd0,
	0x6f, 0x96, 0x36, 0xac, 0x4c, 0xf2, 0x39, 0xda, 0x88, 0x06, 0x20, 0x6d, 0x5d, 0x94, 0xff, 0x36,
	0x4b, 0x2d, 0x92, 0x69, 0xc3, 0xca, 0x24, 0x5f, 0xc7, 0x0e, 0x53, 0xd7, 0x41, 0xec, 0x30, 0x9d,
	0xe6, 0xa9, 0xc3, 0x49, 0xf6, 0x8e, 0x1d, 0xa6, 0xd2, 0x7f, 0xec, 0x30, 0x9d, 0xf4, 0xa9, 0xc3,
	0x49, 0x6e, 0x8f, 0x1d, 0xa6, 0x2e, 0x83, 0xd8, 0x61, 0xfa, 0x4a, 0xa8, 0x9e, 0xc2, 0xed, 0x30,
	0x88, 0x60, 0x20, 0xcf, 0x47, 0x8f, 0x20, 0x17, 0xd2, 0x11, 0xda, 0x4c, 0x10, 0x54, 0xda, 0x1a,
	0x28, 0x6f, 0x5d, 0xc7, 0x60, 0xd5, 0x1e, 0x2c, 0xf3, 0xeb, 0x1d, 0x36, 0xce, 0x80, 0x5b, 0x53,
	0x17, 0x1b, 0x45, 0xef, 0x99, 0x4e, 0x1c, 0xe5, 0xcd, 0x99, 0x7a, 0x11, 0xe4, 0x7b, 0x09, 0x96,
	0xeb, 0xbe, 0x77, 0x8e, 0xfd, 0x30, 0xca, 0xd1, 0x14, 0x25, 0xde, 0x49, 0xfe, 0xdf, 0x3d, 0x75,
	0x0f, 0xca, 0x7f, 0x4d, 0x57, 0x8a, 0xb2, 0x37, 0xa7, 0x19, 0x30, 0x82, 0xa7, 0x5d, 0xaa, 0xf2,
	0xc6, 0x0c, 0x2d, 0xf7, 0x56, 0xdf, 0x7c, 0xba, 0x31, 0xb0, 0xc9, 0xd9, 0xf8, 0xb4, 0xd2, 0xf3,
	0x86, 0xbb, 0xfd, 0x71, 0xaf, 0xb7, 0x7b, 0xfe, 0xe2, 0xcd, 0x6b, 0x97, 0xf0, 0x1f, 0x8e, 0x82,
	0x53, 0xfe, 0x7b, 0xd2, 0x7f, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xcb, 0x6e, 0x37, 0x66,
	0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyResponse, error)
	UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyResponse, error)
	DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error)
	ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesResponse, error)
}

type dataServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataServiceClient(cc *grpc.ClientConn) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyResponse, error) {
	out := new(CreateStrategyResponse)
	err := c.cc.Invoke(ctx, "/protos.DataService/CreateStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyResponse, error) {
	out := new(UpdateStrategyResponse)
	err := c.cc.Invoke(ctx, "/protos.DataService/UpdateStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error) {
	out := new(DeleteStrategyResponse)
	err := c.cc.Invoke(ctx, "/protos.DataService/DeleteStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesResponse, error) {
	out := new(ListStrategiesResponse)
	err := c.cc.Invoke(ctx, "/protos.DataService/ListStrategies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	CreateStrategy(context.Context, *CreateStrategyRequest) (*CreateStrategyResponse, error)
	UpdateStrategy(context.Context, *UpdateStrategyRequest) (*UpdateStrategyResponse, error)
	DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyResponse, error)
	ListStrategies(context.Context, *ListStrategiesRequest) (*ListStrategiesResponse, error)
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) CreateStrategy(ctx context.Context, req *CreateStrategyRequest) (*CreateStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStrategy not implemented")
}
func (*UnimplementedDataServiceServer) UpdateStrategy(ctx context.Context, req *UpdateStrategyRequest) (*UpdateStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategy not implemented")
}
func (*UnimplementedDataServiceServer) DeleteStrategy(ctx context.Context, req *DeleteStrategyRequest) (*DeleteStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStrategy not implemented")
}
func (*UnimplementedDataServiceServer) ListStrategies(ctx context.Context, req *ListStrategiesRequest) (*ListStrategiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStrategies not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_CreateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CreateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataService/CreateStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CreateStrategy(ctx, req.(*CreateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_UpdateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).UpdateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataService/UpdateStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).UpdateStrategy(ctx, req.(*UpdateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_DeleteStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).DeleteStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataService/DeleteStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).DeleteStrategy(ctx, req.(*DeleteStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ListStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataService/ListStrategies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListStrategies(ctx, req.(*ListStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStrategy",
			Handler:    _DataService_CreateStrategy_Handler,
		},
		{
			MethodName: "UpdateStrategy",
			Handler:    _DataService_UpdateStrategy_Handler,
		},
		{
			MethodName: "DeleteStrategy",
			Handler:    _DataService_DeleteStrategy_Handler,
		},
		{
			MethodName: "ListStrategies",
			Handler:    _DataService_ListStrategies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}

// StrategyEvaluatorClient is the client API for StrategyEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StrategyEvaluatorClient interface {
	Evaluate(ctx context.Context, in *EvaulateStrategyRequest, opts ...grpc.CallOption) (*EvaluateStrategyResponse, error)
}

type strategyEvaluatorClient struct {
	cc *grpc.ClientConn
}

func NewStrategyEvaluatorClient(cc *grpc.ClientConn) StrategyEvaluatorClient {
	return &strategyEvaluatorClient{cc}
}

func (c *strategyEvaluatorClient) Evaluate(ctx context.Context, in *EvaulateStrategyRequest, opts ...grpc.CallOption) (*EvaluateStrategyResponse, error) {
	out := new(EvaluateStrategyResponse)
	err := c.cc.Invoke(ctx, "/protos.StrategyEvaluator/Evaluate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyEvaluatorServer is the server API for StrategyEvaluator service.
type StrategyEvaluatorServer interface {
	Evaluate(context.Context, *EvaulateStrategyRequest) (*EvaluateStrategyResponse, error)
}

// UnimplementedStrategyEvaluatorServer can be embedded to have forward compatible implementations.
type UnimplementedStrategyEvaluatorServer struct {
}

func (*UnimplementedStrategyEvaluatorServer) Evaluate(ctx context.Context, req *EvaulateStrategyRequest) (*EvaluateStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}

func RegisterStrategyEvaluatorServer(s *grpc.Server, srv StrategyEvaluatorServer) {
	s.RegisterService(&_StrategyEvaluator_serviceDesc, srv)
}

func _StrategyEvaluator_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaulateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyEvaluatorServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.StrategyEvaluator/Evaluate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyEvaluatorServer).Evaluate(ctx, req.(*EvaulateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StrategyEvaluator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.StrategyEvaluator",
	HandlerType: (*StrategyEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _StrategyEvaluator_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}

// SymbolServiceClient is the client API for SymbolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SymbolServiceClient interface {
	GetPriceHistory(ctx context.Context, in *GetPriceHistoryRequest, opts ...grpc.CallOption) (*GetPriceHistoryResponse, error)
}

type symbolServiceClient struct {
	cc *grpc.ClientConn
}

func NewSymbolServiceClient(cc *grpc.ClientConn) SymbolServiceClient {
	return &symbolServiceClient{cc}
}

func (c *symbolServiceClient) GetPriceHistory(ctx context.Context, in *GetPriceHistoryRequest, opts ...grpc.CallOption) (*GetPriceHistoryResponse, error) {
	out := new(GetPriceHistoryResponse)
	err := c.cc.Invoke(ctx, "/protos.SymbolService/GetPriceHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SymbolServiceServer is the server API for SymbolService service.
type SymbolServiceServer interface {
	GetPriceHistory(context.Context, *GetPriceHistoryRequest) (*GetPriceHistoryResponse, error)
}

// UnimplementedSymbolServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSymbolServiceServer struct {
}

func (*UnimplementedSymbolServiceServer) GetPriceHistory(ctx context.Context, req *GetPriceHistoryRequest) (*GetPriceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriceHistory not implemented")
}

func RegisterSymbolServiceServer(s *grpc.Server, srv SymbolServiceServer) {
	s.RegisterService(&_SymbolService_serviceDesc, srv)
}

func _SymbolService_GetPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymbolServiceServer).GetPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SymbolService/GetPriceHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymbolServiceServer).GetPriceHistory(ctx, req.(*GetPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SymbolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.SymbolService",
	HandlerType: (*SymbolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPriceHistory",
			Handler:    _SymbolService_GetPriceHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerServiceClient interface {
	OpenPosition(ctx context.Context, in *OpenPositionRequest, opts ...grpc.CallOption) (*OpenPositionResponse, error)
	ClosePosition(ctx context.Context, in *ClosePositionRequest, opts ...grpc.CallOption) (*ClosePositionResponse, error)
}

type brokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewBrokerServiceClient(cc *grpc.ClientConn) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) OpenPosition(ctx context.Context, in *OpenPositionRequest, opts ...grpc.CallOption) (*OpenPositionResponse, error) {
	out := new(OpenPositionResponse)
	err := c.cc.Invoke(ctx, "/protos.BrokerService/OpenPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) ClosePosition(ctx context.Context, in *ClosePositionRequest, opts ...grpc.CallOption) (*ClosePositionResponse, error) {
	out := new(ClosePositionResponse)
	err := c.cc.Invoke(ctx, "/protos.BrokerService/ClosePosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
type BrokerServiceServer interface {
	OpenPosition(context.Context, *OpenPositionRequest) (*OpenPositionResponse, error)
	ClosePosition(context.Context, *ClosePositionRequest) (*ClosePositionResponse, error)
}

// UnimplementedBrokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerServiceServer struct {
}

func (*UnimplementedBrokerServiceServer) OpenPosition(ctx context.Context, req *OpenPositionRequest) (*OpenPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenPosition not implemented")
}
func (*UnimplementedBrokerServiceServer) ClosePosition(ctx context.Context, req *ClosePositionRequest) (*ClosePositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePosition not implemented")
}

func RegisterBrokerServiceServer(s *grpc.Server, srv BrokerServiceServer) {
	s.RegisterService(&_BrokerService_serviceDesc, srv)
}

func _BrokerService_OpenPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).OpenPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BrokerService/OpenPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).OpenPosition(ctx, req.(*OpenPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_ClosePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ClosePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BrokerService/ClosePosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).ClosePosition(ctx, req.(*ClosePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenPosition",
			Handler:    _BrokerService_OpenPosition_Handler,
		},
		{
			MethodName: "ClosePosition",
			Handler:    _BrokerService_ClosePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos.proto",
}
