# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos_pb2 as protos__pb2


class DataServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateStrategy = channel.unary_unary(
        '/protos.DataService/CreateStrategy',
        request_serializer=protos__pb2.CreateStrategyRequest.SerializeToString,
        response_deserializer=protos__pb2.CreateStrategyResponse.FromString,
        )
    self.UpdateStrategy = channel.unary_unary(
        '/protos.DataService/UpdateStrategy',
        request_serializer=protos__pb2.UpdateStrategyRequest.SerializeToString,
        response_deserializer=protos__pb2.UpdateStrategyResponse.FromString,
        )
    self.DeleteStrategy = channel.unary_unary(
        '/protos.DataService/DeleteStrategy',
        request_serializer=protos__pb2.DeleteStrategyRequest.SerializeToString,
        response_deserializer=protos__pb2.DeleteStrategyResponse.FromString,
        )
    self.ListStrategies = channel.unary_unary(
        '/protos.DataService/ListStrategies',
        request_serializer=protos__pb2.ListStrategiesRequest.SerializeToString,
        response_deserializer=protos__pb2.ListStrategiesResponse.FromString,
        )
    self.GetPriceHistory = channel.unary_unary(
        '/protos.DataService/GetPriceHistory',
        request_serializer=protos__pb2.GetPriceHistoryRequest.SerializeToString,
        response_deserializer=protos__pb2.GetPriceHistoryResponse.FromString,
        )
    self.AddCandlestick = channel.unary_unary(
        '/protos.DataService/AddCandlestick',
        request_serializer=protos__pb2.AddCandlestickRequest.SerializeToString,
        response_deserializer=protos__pb2.AddCandlestickResponse.FromString,
        )
    self.CreateUser = channel.unary_unary(
        '/protos.DataService/CreateUser',
        request_serializer=protos__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=protos__pb2.CreateUserResponse.FromString,
        )
    self.UpdateUser = channel.unary_unary(
        '/protos.DataService/UpdateUser',
        request_serializer=protos__pb2.UpdateUserRequest.SerializeToString,
        response_deserializer=protos__pb2.UpdateUserResponse.FromString,
        )
    self.ListUsers = channel.unary_unary(
        '/protos.DataService/ListUsers',
        request_serializer=protos__pb2.ListUsersRequest.SerializeToString,
        response_deserializer=protos__pb2.ListUsersResponse.FromString,
        )


class DataServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateStrategy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateStrategy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteStrategy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListStrategies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPriceHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddCandlestick(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateStrategy': grpc.unary_unary_rpc_method_handler(
          servicer.CreateStrategy,
          request_deserializer=protos__pb2.CreateStrategyRequest.FromString,
          response_serializer=protos__pb2.CreateStrategyResponse.SerializeToString,
      ),
      'UpdateStrategy': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateStrategy,
          request_deserializer=protos__pb2.UpdateStrategyRequest.FromString,
          response_serializer=protos__pb2.UpdateStrategyResponse.SerializeToString,
      ),
      'DeleteStrategy': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteStrategy,
          request_deserializer=protos__pb2.DeleteStrategyRequest.FromString,
          response_serializer=protos__pb2.DeleteStrategyResponse.SerializeToString,
      ),
      'ListStrategies': grpc.unary_unary_rpc_method_handler(
          servicer.ListStrategies,
          request_deserializer=protos__pb2.ListStrategiesRequest.FromString,
          response_serializer=protos__pb2.ListStrategiesResponse.SerializeToString,
      ),
      'GetPriceHistory': grpc.unary_unary_rpc_method_handler(
          servicer.GetPriceHistory,
          request_deserializer=protos__pb2.GetPriceHistoryRequest.FromString,
          response_serializer=protos__pb2.GetPriceHistoryResponse.SerializeToString,
      ),
      'AddCandlestick': grpc.unary_unary_rpc_method_handler(
          servicer.AddCandlestick,
          request_deserializer=protos__pb2.AddCandlestickRequest.FromString,
          response_serializer=protos__pb2.AddCandlestickResponse.SerializeToString,
      ),
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=protos__pb2.CreateUserRequest.FromString,
          response_serializer=protos__pb2.CreateUserResponse.SerializeToString,
      ),
      'UpdateUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUser,
          request_deserializer=protos__pb2.UpdateUserRequest.FromString,
          response_serializer=protos__pb2.UpdateUserResponse.SerializeToString,
      ),
      'ListUsers': grpc.unary_unary_rpc_method_handler(
          servicer.ListUsers,
          request_deserializer=protos__pb2.ListUsersRequest.FromString,
          response_serializer=protos__pb2.ListUsersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.DataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class StrategyEvaluatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Evaluate = channel.unary_unary(
        '/protos.StrategyEvaluator/Evaluate',
        request_serializer=protos__pb2.EvaulateStrategyRequest.SerializeToString,
        response_deserializer=protos__pb2.EvaluateStrategyResponse.FromString,
        )


class StrategyEvaluatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Evaluate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StrategyEvaluatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Evaluate': grpc.unary_unary_rpc_method_handler(
          servicer.Evaluate,
          request_deserializer=protos__pb2.EvaulateStrategyRequest.FromString,
          response_serializer=protos__pb2.EvaluateStrategyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.StrategyEvaluator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BrokerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCurrentSessions = channel.unary_unary(
        '/protos.BrokerService/GetCurrentSessions',
        request_serializer=protos__pb2.GetCurrentSessionsRequest.SerializeToString,
        response_deserializer=protos__pb2.GetCurrentSessionsResponse.FromString,
        )
    self.OpenSession = channel.unary_unary(
        '/protos.BrokerService/OpenSession',
        request_serializer=protos__pb2.OpenSessionRequest.SerializeToString,
        response_deserializer=protos__pb2.OpenSessionResponse.FromString,
        )
    self.OpenPosition = channel.unary_unary(
        '/protos.BrokerService/OpenPosition',
        request_serializer=protos__pb2.OpenPositionRequest.SerializeToString,
        response_deserializer=protos__pb2.OpenPositionResponse.FromString,
        )
    self.ClosePosition = channel.unary_unary(
        '/protos.BrokerService/ClosePosition',
        request_serializer=protos__pb2.ClosePositionRequest.SerializeToString,
        response_deserializer=protos__pb2.ClosePositionResponse.FromString,
        )
    self.GetBrokerPriceHistory = channel.unary_unary(
        '/protos.BrokerService/GetBrokerPriceHistory',
        request_serializer=protos__pb2.GetBrokerPriceHistoryRequest.SerializeToString,
        response_deserializer=protos__pb2.GetBrokerPriceHistoryResponse.FromString,
        )
    self.SubscribeToPriceChanges = channel.unary_unary(
        '/protos.BrokerService/SubscribeToPriceChanges',
        request_serializer=protos__pb2.SubscribeToPriceChangesRequest.SerializeToString,
        response_deserializer=protos__pb2.SubscribeToPriceChangesResponse.FromString,
        )
    self.RegisterBroker = channel.unary_unary(
        '/protos.BrokerService/RegisterBroker',
        request_serializer=protos__pb2.RegisterBrokerRequest.SerializeToString,
        response_deserializer=protos__pb2.RegisterBrokerResponse.FromString,
        )


class BrokerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCurrentSessions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClosePosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBrokerPriceHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeToPriceChanges(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterBroker(self, request, context):
    """used by the broker services to notify the router of their existence - maybe a service mesh is better
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCurrentSessions': grpc.unary_unary_rpc_method_handler(
          servicer.GetCurrentSessions,
          request_deserializer=protos__pb2.GetCurrentSessionsRequest.FromString,
          response_serializer=protos__pb2.GetCurrentSessionsResponse.SerializeToString,
      ),
      'OpenSession': grpc.unary_unary_rpc_method_handler(
          servicer.OpenSession,
          request_deserializer=protos__pb2.OpenSessionRequest.FromString,
          response_serializer=protos__pb2.OpenSessionResponse.SerializeToString,
      ),
      'OpenPosition': grpc.unary_unary_rpc_method_handler(
          servicer.OpenPosition,
          request_deserializer=protos__pb2.OpenPositionRequest.FromString,
          response_serializer=protos__pb2.OpenPositionResponse.SerializeToString,
      ),
      'ClosePosition': grpc.unary_unary_rpc_method_handler(
          servicer.ClosePosition,
          request_deserializer=protos__pb2.ClosePositionRequest.FromString,
          response_serializer=protos__pb2.ClosePositionResponse.SerializeToString,
      ),
      'GetBrokerPriceHistory': grpc.unary_unary_rpc_method_handler(
          servicer.GetBrokerPriceHistory,
          request_deserializer=protos__pb2.GetBrokerPriceHistoryRequest.FromString,
          response_serializer=protos__pb2.GetBrokerPriceHistoryResponse.SerializeToString,
      ),
      'SubscribeToPriceChanges': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeToPriceChanges,
          request_deserializer=protos__pb2.SubscribeToPriceChangesRequest.FromString,
          response_serializer=protos__pb2.SubscribeToPriceChangesResponse.SerializeToString,
      ),
      'RegisterBroker': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterBroker,
          request_deserializer=protos__pb2.RegisterBrokerRequest.FromString,
          response_serializer=protos__pb2.RegisterBrokerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.BrokerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
